#!/bin/bash

./run_deepspeed v2 1 >/dev/null 2>&1 &
./run_deepspeed v3 2 >/dev/null 2>&1 &
./run_deepspeed v4 3 >/dev/null 2>&1 &
./run_deepspeed v5 4 >/dev/null 2>&1 &
./run_deepspeed v6 5 >/dev/null 2>&1 &
./run_deepspeed v7 6 >/dev/null 2>&1 &
./run_deepspeed v8 7 >/dev/null 2>&1 &

./run_deepspeed v1 0
