#!/usr/bin/bash

./run_deepspeed 10.28.1.2 1 >/dev/null 2>&1 &
./run_deepspeed 10.28.1.3 2 >/dev/null 2>&1 &
./run_deepspeed 10.28.1.4 3 >/dev/null 2>&1 &
./run_deepspeed 10.28.1.5 4 >/dev/null 2>&1 &
./run_deepspeed 10.28.1.6 5 >/dev/null 2>&1 &
./run_deepspeed 10.28.1.7 6 >/dev/null 2>&1 &
./run_deepspeed 10.28.1.8 7 >/dev/null 2>&1 &

./run_deepspeed 10.28.1.1 0
