#!/bin/bash

rsync -rtlpzzP --filter=":- .gitignore" --exclude='.git*' . $1:/root/hap && \
ssh $1 -T <<EOF
    pkill python
    cd /root/hap
    export PATH=/usr/local/cuda/bin:/opt/conda/bin:\$PATH
    bash deepspeed/run.sh $2
EOF
